Permissions fix
nfqakademija/streetwise-sophisticated-hackers pull request #4
Opened 2017-04-21 16:42 UTC by eleggua999

Perdariau permissions ir twig actions atvaizdavimą pagal roles.

Esmė tokia, kad extendinau EasyAdminTwigExtension ir overridinau defaultinį servisą (easyadmin.twig.extension). Jam injectinu papildomai token_storage (ištraukti current Userį) ir access.decision_manager (naudoti rolių hierarchiją). Pridėjau jam naują funkciją, kuri priklausomai nuo konfigūracijos ir naudotojo rolės grąžina leidžiamų actions masyvą (iš esmės perrašyta EasyAdmin extensiono funkcija, tačiau negalėjau jos tiesiog overridinti, nes reikia priimti papildomą parametrą). Overridinau twig templatus, kad naudotų šitą naują funkciją vietoje senos, defaultinės EasyAdmino ir papildomai jai perdaviau entity. Overridinau dar kitą funkciją, kuri susijusi su actions atvaizdavimu.
Taip pat sukūriau HasOwnerInterface, kurį implementiną Entičiai. Jis turi funkciją getOwner, kuri grąžina Userį. Kiekvienas Entity grąžina savo ownerį (User - save; Homework, Lecture - lektorių; News turėtų grąžinti autorių). Owneris gali redaguoti savo sukurtą paskaitą/namų darbą/naujieną ir t. t. Vietoje 3 Voterių sukurtas 1 (AppVoter), kuris votina ant Entičių, kurie implementiną šitą interfeisą.
Parašiau naują konfigą prie kiekvieno Entičio - access_role. Jį naudoja Voteris ir Extensionas, ir sprendžia, kurios rolės Useris gali kurti naują Entity (paskaitai - nuo ROLE_LECTOR, naują naudotoją gali kurti tik ROLE_ADMIN).

Kas iš to?
Naudojama rolų hierarchija.
Prie kiekvieno Entity liste galima matyti leidžiamus actions (anksčiau rodė tik pagal rolę, dabar - apskritai pagal taises).
Nereikia naudoti twige ifų ir kreivų funkcijų.
Nebereikia kaskart kurti Voterį, jei neapibrėžiama jokia custom logiką.
Nebreikia konfigūruoti kiekvieno actiono - užtenka nurodyti access_role prie Entičio. Jei nenurodyta, naują Entity bus leidžiama kurti tik adminui.

Taip pat į twigus ir kontrolerius pridėtos atitinkamai path ir redirect funkcijos (vietoje hardcodintų nuorodų).

2017-04-24 19:23 UTC, mechpave requested changes
Nice, patiko idėja turėti vieną voter'į objektams su owneriu

2017-04-24 19:23 UTC, mechpave commented on src/AppBundle/Controller/Admin/HomeworkController.php
> +            return $this->redirect($this->get('router')->generate('easyadmin', $queryParameters));
Controlleriai turi visokiu helper metodu, kaip pvz $this->redirectToRoute($route, $params);
Nebent sitas neextendina Symfonio Controller klases is FrameworkBundle.
Siaip viskas ok, galima ir taip, bet keep in mind

2017-04-24 19:23 UTC, mechpave commented on src/AppBundle/Entity/Homework.php
> +     * @return User
`{@inheritdoc}` vietoj `@return User`

2017-04-24 19:23 UTC, mechpave commented on src/AppBundle/Entity/Lecture.php
> +     * @return User
irgi

2017-04-24 19:23 UTC, mechpave commented on src/AppBundle/Entity/User.php
> +     * @return User
i cia

2017-04-24 19:23 UTC, mechpave commented on src/AppBundle/Security/AppVoter.php
> +        $reflect = new \ReflectionClass($subject);
Cia is dokumentacijos? Siaip ReflectionClass naudojamas pakankamai retais atvejais ir man kazkodel atrodo, kad cia galima ir be jo apseiti. Bet kol kas nieko nekeisk, cia tiesiog pasizymiu ka reikes pasiziureti iki susitikimo

2017-04-24 19:23 UTC, mechpave commented on src/AppBundle/Security/AppVoter.php
> +        if(isset($this->configManager->getEntityConfig($entityName)['access_role']))
Net ir vienos eilutes if`uose naudojam skliaustus { }. Kai kurie PHP navarotai nelabai padeda skaitomumui :D

2017-04-24 19:23 UTC, mechpave commented on src/AppBundle/Twig/AppExtension.php
> +        if (null === $token = $this->tokenStorage->getToken()) {
Vengiam priskirimu if'u salygose:
```
$token = $this->tokenStorage->getToken();
if (null === $token) {
return [];
}
```
Taip paprasciau skaityti koda

2017-04-24 19:23 UTC, mechpave commented on src/AppBundle/Twig/AppExtension.php
> +        if($entity instanceof HasOwnerInterface && $entity->getOwner()->getId() == $user->getId() || $this->decisionManager->decide($token, ['ROLE_ADMIN'])) {
Sunkokai skaitomas if'as
Nors ir neprivaloma, čia gal būtų nebloga vieta papildomai apskliausti pirmą sąlygą:
```
if(($entity instanceof HasOwnerInterface && $entity->getOwner()->getId() == $user->getId()) || $this->decisionManager->decide($token, ['ROLE_ADMIN']))
```
Iš kodo pusės niekas nesikeičia, bet tokiam kaip aš jau ramiau, nes akys nebėgioja tarp visų operatorių :)

Dar spėju, kad userius galima lyginti tiesiog taip: `$entity->getOwner() == $user` (nieko nežinau ar čia gera praktika ir pan., man tiesiog labai norisi šitam if'e sumažinti kodo :) )

2017-04-24 19:23 UTC, mechpave commented on src/AppBundle/Twig/AppExtension.php
> +        if($action == 'search')
```
if($action == 'search') {
    return $parent;
}
```

2017-04-24 19:23 UTC, mechpave commented on src/AppBundle/Twig/AppExtension.php
> +        if (null === $token = $this->tokenStorage->getToken()) {
priskyrimas sąlygoje

2017-04-24 19:23 UTC, mechpave commented on src/AppBundle/Twig/AppExtension.php
> +        if(isset($this->getEntityConfiguration($entityName)['access_role']))
{}

2017-04-25 16:50 UTC, eleggua999 commented on src/AppBundle/Security/AppVoter.php
> +        $reflect = new \ReflectionClass($subject);
Kokios dokumentacijos? Aš šitą darau, kad iš Config Managerio Entity configus išsitraukti, nes EasyAdminas vadina Entičius klasių vardais. Čia bet koks būdas tiks, kuris iš objekto klasės vardą leis išgaut.

2017-04-25 19:33 UTC, mechpave approved these changes

2017-04-25 20:17 UTC, eleggua999 commented
%&^#

2017-04-25 20:53 UTC, merged